### ISSUE TITLE
Nastulogue.exe does not exist

### ISSUE THREAD

**Issue by BrandiBlitz** [CupCake-Team/Natsulogue#1]
I downloaded the mod files and looked through them. The Natsulogue.exe launcher does not exist

**Comment by NekoLaiS** [comment]
Download this:
https://github.com/CupCake-Team/Natsulogue/releases/tag/v.0.3.5

**Comment by BrandiBlitz** [comment]
> Download this:
> 
> https://github.com/CupCake-Team/Natsulogue/releases/tag/v.0.3.5

Thank you so much!
